language: node_js
node_js:
  - 'node'

before_install:
  - echo "//registry.npmjs.org/" > .npmrc

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    tags: true
