language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

after_success:
  - cd dist
  - git init
  - git add .
  - git config user.name cody1991
  - git config user.email "476490767@qq.com"
  - git commit -m "自动更新pages"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/cody1991/vue3-typescript" master:master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    tags: true
