language: node_js
node_js:
  - 'node'

before_install:
  - echo "npm config set registry https://registry.npmjs.org/"

cache: npm

script: npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    tags: true
